/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciointerfazgrafica3;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Criss Candioti
 */
public class Ventana extends javax.swing.JFrame {
    
    private DefaultTableModel modelo = new DefaultTableModel() {
        
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
        
    };

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        armarTabla();
        ocultarBoton();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProducto = new javax.swing.JTable();
        LabelNombre = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        JTNombre = new javax.swing.JTextField();
        JTPrecio = new javax.swing.JTextField();
        JBAgregar = new javax.swing.JButton();
        JBotonAgregarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "ALIMENTO", "ELECTRONICA", "ROPA" }));
        jComboBoxCategoria.setName(""); // NOI18N
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 12, -1, -1));

        TablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProducto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 91));

        LabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        LabelNombre.setText("NOMBRE");
        getContentPane().add(LabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        LabelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        LabelPrecio.setText("PRECIO");
        getContentPane().add(LabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));
        getContentPane().add(JTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 62, 181, -1));
        getContentPane().add(JTPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 111, 181, -1));

        JBAgregar.setText("CONFIRMAR");
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(JBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        JBotonAgregarProducto.setText("AGREGAR PRODUCTO");
        JBotonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotonAgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(JBotonAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 11, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejerciciointerfazgrafica3/112121.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 750, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void JBotonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonAgregarProductoActionPerformed
        
        if (jComboBoxCategoria.getSelectedIndex() != 0) {
            mostrarBoton();
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una categoria");
        }

    }//GEN-LAST:event_JBotonAgregarProductoActionPerformed

    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
        
        try {
            String nombre = JTNombre.getText();
            double precio = Double.parseDouble(JTPrecio.getText());
            String categoria = (String) jComboBoxCategoria.getSelectedItem();
            
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese el nombre del producto");
//            } else if (jComboBoxCategoria.getSelectedIndex() == 0) {
//                JOptionPane.showMessageDialog(this, "Seleccione una categoria gil!!");
            } else {
                Producto aux = new Producto(categoria, nombre, precio);
                cargarDatos(aux);
                ocultarBoton();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese numero en el campo precio");
        }

    }//GEN-LAST:event_JBAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregar;
    private javax.swing.JButton JBotonAgregarProducto;
    private javax.swing.JTextField JTNombre;
    private javax.swing.JTextField JTPrecio;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JTable TablaProducto;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void armarTabla() {
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("PRECIO");
        TablaProducto.setModel(modelo);
    }
    
    private void ocultarBoton() {
        LabelNombre.setVisible(false);
        LabelPrecio.setVisible(false);
        JTNombre.setVisible(false);
        JTPrecio.setVisible(false);
        JBAgregar.setVisible(false);
        JBotonAgregarProducto.setVisible(true);
        JTNombre.setText("");
        JTPrecio.setText("");
        jComboBoxCategoria.setVisible(true);
    }
    
    private void mostrarBoton() {
        LabelNombre.setVisible(true);
        LabelPrecio.setVisible(true);
        JTNombre.setVisible(true);
        JTPrecio.setVisible(true);
        JBAgregar.setVisible(true);
        JBotonAgregarProducto.setVisible(false);
        jComboBoxCategoria.setVisible(false);
    }
    
    private void cargarDatos(Producto index) {
        modelo.addRow(new Object[]{index.getCategoria(), index.getNombre(), index.getPrecio()});
        
    }
}
